backend:
  name: github
  repo: justin88-creator/Trenz_homes-props
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "properties"
    label: "Properties"

    files:
      - label: "Property Listings"
        name: "propertyListings"
        file: "data/properties.json"

        fields:
          - label: "Properties"
            name: "properties"
            widget: "list"

            fields:
              - label: "Title"
                name: "title"
                widget: "string"

              - label: "Location"
                name: "location"
                widget: "string"

              - label: "Price"
                name: "price"
                widget: "string"

              - label: "Image"
                name: "image"
                widget: "image"

              - label: "Bedrooms"
                name: "bedrooms"
                widget: "number"

              - label: "Bathrooms"
                name: "bathrooms"
                widget: "number"

              - label: "Size"
                name: "size"
                widget: "string"

              - label: "Status"
                name: "status"
                widget: "string"

              - label: "Description"
                name: "description"
                widget: "text"

              - label: "Inspection Fee"
                name: "inspectionFee"
                widget: "number"