backend:
  name: github
  repo: justin88-creator/Trenz_home-props
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "content/properties"
    create: true

    fields:
      - { label: "Property Title", name: "title", widget: "string" }

      - { label: "Location", name: "location", widget: "string" }

      - { label: "Price", name: "price", widget: "string" }

      - { label: "Bedrooms", name: "bedrooms", widget: "number" }

      - { label: "Bathrooms", name: "bathrooms", widget: "number" }

      - { label: "Size", name: "size", widget: "string" }

      - { label: "Status", name: "status", widget: "string" }

      - { label: "Image", name: "image", widget: "image" }